<#
.SYNOPSIS
  Install this repository as a Claude Code plugin, for real, and record what
  happened.

.DESCRIPTION
  Milestone 6.4 asks whether Claude Code actually loads this plugin and finds
  its skills. That question cannot be answered by a filesystem fixture, and the
  milestone's authorization is explicit that simulating one and calling it
  integration-verified is not acceptable.

  So this drives the real `claude` CLI: adds this checkout as a marketplace,
  installs the plugin, reads back the component inventory, and writes the
  transcript to docs/evidence/. A reviewer can re-run it and compare.

  NOT part of CI, and deliberately so. It needs the `claude` CLI on PATH, and
  it writes to the user's own plugin configuration in ~/.claude -- a CI job has
  no business doing either. Everything CI *can* check without touching a user's
  machine lives in tests/helpers/plugin-package-tests.ps1.

  Leaves the machine as it found it: the marketplace and plugin are removed
  again unless -Keep is given.

.PARAMETER Keep
  Leave the plugin installed after capturing evidence.

.PARAMETER OutputPath
  Where to write the transcript. Defaults to
  docs/evidence/plugin-load-transcript.md.
#>
[CmdletBinding()]
param(
  [switch]$Keep,
  [string]$OutputPath = $null
)

$ErrorActionPreference = "Continue"

$script:repo = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
$repo = $script:repo
if (-not $OutputPath) { $OutputPath = Join-Path $repo "docs/evidence/plugin-load-transcript.md" }

$claude = Get-Command claude -ErrorAction SilentlyContinue
if (-not $claude) {
  Write-Host "[SKIP] The 'claude' CLI is not on PATH."
  Write-Host "  This capture drives the real plugin installer; without it there is nothing to record."
  Write-Host "  Install Claude Code, then re-run:"
  Write-Host "    pwsh -File scripts/capture-plugin-load-evidence.ps1"
  exit 0
}

$transcript = New-Object System.Collections.Generic.List[string]

function ConvertTo-Redacted {
  # This transcript is committed, so it must not carry the capturing machine's
  # paths. Milestone 4.5 shipped exactly this leak once already and
  # LOCAL-PATH-002 caught it; redacting here means a maintainer cannot
  # reintroduce it by re-running the capture on their own machine.
  param([string]$Text)
  if ($null -eq $Text) { return "" }
  $result = $Text.Replace($script:repo, "<repo>")
  $home = [System.Environment]::GetFolderPath([System.Environment+SpecialFolder]::UserProfile)
  if ($home) { $result = $result.Replace($home, "<home>") }
  # Belt and braces: any surviving home-directory path shape, whatever produced
  # it. Single-quoted so the regex metacharacters and quotes survive verbatim.
  foreach ($shape in @(
    @{ Pattern = '(/Users/)[^/\s"'']+'; Replacement = '$1<user>' },
    @{ Pattern = '(/home/)[^/\s"'']+'; Replacement = '$1<user>' },
    @{ Pattern = '(C:\\Users\\)[^\\\s"'']+'; Replacement = '$1<user>' }
  )) {
    $result = [regex]::Replace($result, $shape.Pattern, $shape.Replacement)
  }
  return $result
}

function Add-Line { param([string]$Text) $line = ConvertTo-Redacted $Text; $script:transcript.Add($line) | Out-Null; Write-Host $line }

function Invoke-Claude {
  param([string[]]$Arguments)
  Add-Line ""
  Add-Line ('$ claude ' + ($Arguments -join " "))
  $previous = $ErrorActionPreference
  $ErrorActionPreference = "Continue"
  try {
    $out = & claude @Arguments 2>&1
    $code = $LASTEXITCODE
  } finally { $ErrorActionPreference = $previous }
  # Indented for readability, but never on an empty line -- "  " on a blank
  # line is trailing whitespace, and `git diff --check` is right to complain.
  foreach ($line in @($out)) {
    $text = [string]$line
    if ([string]::IsNullOrWhiteSpace($text)) { Add-Line "" } else { Add-Line ("  " + $text) }
  }
  Add-Line ("  [exit $code]")
  return [pscustomobject]@{ ExitCode = $code; Text = (@($out) | ForEach-Object { [string]$_ }) -join "`n" }
}

Add-Line "# Claude Code plugin load transcript"
Add-Line ""
Add-Line "> Generated by ``scripts/capture-plugin-load-evidence.ps1``. This is a real"
Add-Line "> install through the ``claude`` CLI, not a simulation -- Milestone 6.4 requires"
Add-Line "> that distinction and this file is the evidence for it."
Add-Line ""
Add-Line ("Captured: " + ([datetime]::UtcNow.ToString("yyyy-MM-dd HH:mm:ss", [System.Globalization.CultureInfo]::InvariantCulture)) + " UTC")
Add-Line ("Repository commit: " + (& git -C $repo rev-parse HEAD 2>$null))
Add-Line ("Claude CLI: " + ((& claude --version 2>&1) -join " "))
Add-Line ""
Add-Line '```text'

$marketplaceName = "axiom-pmo"
$pluginName = "axiom-pmo"

# Start from a known state so a leftover install from a previous run does not
# make this look like a success it did not earn.
Invoke-Claude -Arguments @("plugin", "uninstall", $pluginName) | Out-Null
Invoke-Claude -Arguments @("plugin", "marketplace", "remove", $marketplaceName) | Out-Null

$add = Invoke-Claude -Arguments @("plugin", "marketplace", "add", $repo)
$install = Invoke-Claude -Arguments @("plugin", "install", "$pluginName@$marketplaceName")
$details = Invoke-Claude -Arguments @("plugin", "details", $pluginName)
Invoke-Claude -Arguments @("plugin", "list") | Out-Null

Add-Line '```'
Add-Line ""

# ---- What the transcript proves, stated conservatively ------------------

$skillsMatch = [regex]::Match($details.Text, "Skills\s*\((\d+)\)\s*(.*)")
$hooksMatch = [regex]::Match($details.Text, "Hooks\s*\((\d+)\)")
$skillCount = if ($skillsMatch.Success) { [int]$skillsMatch.Groups[1].Value } else { 0 }
$hookCount = if ($hooksMatch.Success) { [int]$hooksMatch.Groups[1].Value } else { 0 }

Add-Line "## What this shows"
Add-Line ""
Add-Line "| | |"
Add-Line "|---|---|"
Add-Line ("| Marketplace added | " + $(if ($add.ExitCode -eq 0) { "yes" } else { "**no** (exit $($add.ExitCode))" }) + " |")
Add-Line ("| Plugin installed | " + $(if ($install.ExitCode -eq 0) { "yes" } else { "**no** (exit $($install.ExitCode))" }) + " |")
Add-Line ("| Skills discovered | " + $skillCount + " |")
Add-Line ("| Hooks registered | " + $hookCount + " |")
if ($skillsMatch.Success -and $skillsMatch.Groups[2].Value) {
  Add-Line ("| Skill names | ``" + $skillsMatch.Groups[2].Value.Trim() + "`` |")
}
Add-Line ""
Add-Line "## What it does not show"
Add-Line ""
Add-Line "- That a skill was *invoked* and behaved correctly. Discovery is what the"
Add-Line "  component inventory reports; behaviour is what the seven skills' own"
Add-Line "  content is responsible for, and is unchanged by packaging."
Add-Line "- Permission-prompt behaviour when a skill runs the validator. That depends"
Add-Line "  on the user's own permission settings and is not captured here."
Add-Line "- Anything about Windows. This transcript is from whichever host ran it;"
Add-Line "  the header records which."
Add-Line ""
Add-Line "The advisory hook is registered but inert: it is opt-in per project via"
Add-Line "``.axiom/hooks.json``, so a fresh install of this plugin changes no behaviour"
Add-Line "until a project asks it to."

$outputDir = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $outputDir)) { New-Item -ItemType Directory -Path $outputDir -Force | Out-Null }
[System.IO.File]::WriteAllText($OutputPath, (($transcript -join "`n") + "`n"), (New-Object System.Text.UTF8Encoding($false)))

if (-not $Keep) {
  Write-Host ""
  Write-Host "Cleaning up (pass -Keep to leave the plugin installed)..."
  & claude plugin uninstall $pluginName 2>&1 | Out-Null
  & claude plugin marketplace remove $marketplaceName 2>&1 | Out-Null
}

Write-Host ""
Write-Host "Transcript written to $OutputPath"
if ($skillCount -lt 1) {
  Write-Host "[FAIL] No skills were discovered. The package is not loading."
  exit 1
}
Write-Host "Summary: PASS=1 FAIL=0"
exit 0
