// `capture-plugin-load-evidence`, ported from scripts/capture-plugin-load-evidence.ps1.
// Drives the real `claude` CLI to install the plugin and record the transcript.
// NOT part of CI (writes to ~/.claude); §8.6 stateful methodology.

import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { spawnSync } from "node:child_process";

export interface PluginEvidenceResult {
  output: string;
  exitCode: number;
}

export function capturePluginLoadEvidence(repoRoot: string, keep: boolean, outputPath: string | null): PluginEvidenceResult {
  const repo = resolve(repoRoot);
  const out = outputPath ?? join(repo, "docs/evidence/plugin-load-transcript.md");

  const claudeProbe = spawnSync("claude", ["--version"], { encoding: "utf8" });
  if (claudeProbe.status !== 0) {
    return { output: "[SKIP] The 'claude' CLI is not on PATH.\n  This capture drives the real plugin installer; without it there is nothing to record.\n", exitCode: 0 };
  }

  const transcript: string[] = [];
  const redact = (text: string): string => {
    let result = text.replaceAll(repo, "<repo>");
    const home = process.env.HOME ?? "";
    if (home) result = result.replaceAll(home, "<home>");
    result = result.replace(/(\/Users\/)[^/\s"']+/g, "$1<user>");
    result = result.replace(/(\/home\/)[^/\s"']+/g, "$1<user>");
    result = result.replace(/(C:\\Users\\)[^\\\s"']+/g, "$1<user>");
    return result;
  };
  const addLine = (text: string) => {
    const line = redact(text);
    transcript.push(line);
    process.stdout.write(line + "\n");
  };

  const invokeClaude = (args: string[]): { exitCode: number; text: string } => {
    addLine("");
    addLine(`$ claude ${args.join(" ")}`);
    const r = spawnSync("claude", args, { encoding: "utf8" });
    const code = r.status ?? 1;
    const out = (r.stdout ?? "") + (r.stderr ?? "");
    for (const line of out.split("\n")) {
      if (line.trim() === "") addLine("");
      else addLine("  " + line);
    }
    addLine(`  [exit ${code}]`);
    return { exitCode: code, text: out };
  };

  addLine("# Claude Code plugin load transcript");
  addLine("");
  addLine("> Generated by `scripts/capture-plugin-load-evidence.ps1`. This is a real");
  addLine("> install through the `claude` CLI, not a simulation -- Milestone 6.4 requires");
  addLine("> that distinction and this file is the evidence for it.");
  addLine("");
  addLine(`Captured: ${new Date().toISOString().replace(/T/, " ").replace(/\.\d{3}Z$/, "")} UTC`);
  addLine(`Repository commit: ${spawnSync("git", ["-C", repo, "rev-parse", "HEAD"], { encoding: "utf8" }).stdout?.trim() ?? ""}`);
  addLine(`Claude CLI: ${claudeProbe.stdout?.trim() ?? ""}`);
  addLine("");
  addLine("```text");

  const marketplaceName = "axiom-pmo";
  const pluginName = "axiom-pmo";

  invokeClaude(["plugin", "uninstall", pluginName]);
  invokeClaude(["plugin", "marketplace", "remove", marketplaceName]);

  const add = invokeClaude(["plugin", "marketplace", "add", repo]);
  const install = invokeClaude(["plugin", "install", `${pluginName}@${marketplaceName}`]);
  const details = invokeClaude(["plugin", "details", pluginName]);
  invokeClaude(["plugin", "list"]);

  addLine("```");
  addLine("");

  const skillsMatch = /Skills\s*\((\d+)\)\s*(.*)/.exec(details.text);
  const hooksMatch = /Hooks\s*\((\d+)\)/.exec(details.text);
  const skillCount = skillsMatch ? Number(skillsMatch[1]) : 0;
  const hookCount = hooksMatch ? Number(hooksMatch[1]) : 0;

  addLine("## What this shows");
  addLine("");
  addLine("| | |");
  addLine("|---|---|");
  addLine(`| Marketplace added | ${add.exitCode === 0 ? "yes" : `**no** (exit ${add.exitCode})`} |`);
  addLine(`| Plugin installed | ${install.exitCode === 0 ? "yes" : `**no** (exit ${install.exitCode})`} |`);
  addLine(`| Skills discovered | ${skillCount} |`);
  addLine(`| Hooks registered | ${hookCount} |`);
  if (skillsMatch && skillsMatch[2]) addLine(`| Skill names | \`${skillsMatch[2].trim()}\` |`);
  addLine("");
  addLine("## What it does not show");
  addLine("");
  addLine("- That a skill was *invoked* and behaved correctly. Discovery is what the");
  addLine("  component inventory reports; behaviour is what the seven skills' own");
  addLine("  content is responsible for, and is unchanged by packaging.");
  addLine("- Permission-prompt behaviour when a skill runs the validator. That depends");
  addLine("  on the user's own permission settings and is not captured here.");
  addLine("- Anything about Windows. This transcript is from whichever host ran it;");
  addLine("  the header records which.");
  addLine("");
  addLine("The advisory hook is registered but inert: it is opt-in per project via");
  addLine("`.axiom/hooks.json`, so a fresh install of this plugin changes no behaviour");
  addLine("until a project asks it to.");

  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, transcript.join("\n") + "\n", "utf8");

  if (!keep) {
    process.stdout.write("\nCleaning up (pass -Keep to leave the plugin installed)...\n");
    spawnSync("claude", ["plugin", "uninstall", pluginName], { encoding: "utf8" });
    spawnSync("claude", ["plugin", "marketplace", "remove", marketplaceName], { encoding: "utf8" });
  }

  process.stdout.write(`\nTranscript written to ${out}\n`);
  if (skillCount < 1) return { output: "[FAIL] No skills were discovered. The package is not loading.\n", exitCode: 1 };
  return { output: "Summary: PASS=1 FAIL=0\n", exitCode: 0 };
}
